//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.21006.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.21006.1.
// 
#pragma warning disable 1591

namespace TicketingOffice.CurrencyExchangeAsmxProxy.AsmxExchange {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.21006.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="CurrencyExchangeServiceSoap", Namespace="http://Fabrikam.com")]
    public partial class CurrencyExchangeService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback BuyOperationCompleted;
        
        private System.Threading.SendOrPostCallback SellOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public CurrencyExchangeService() {
            this.Url = global::TicketingOffice.CurrencyExchangeAsmxProxy.Properties.Settings.Default.CurrencyExchangeAsmxProxy_AsmxExchange_CurrencyExchangeService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event BuyCompletedEventHandler BuyCompleted;
        
        /// <remarks/>
        public event SellCompletedEventHandler SellCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Fabrikam.com/Buy", RequestNamespace="http://Fabrikam.com", ResponseNamespace="http://Fabrikam.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public double Buy(Currencies currency, double amount) {
            object[] results = this.Invoke("Buy", new object[] {
                        currency,
                        amount});
            return ((double)(results[0]));
        }
        
        /// <remarks/>
        public void BuyAsync(Currencies currency, double amount) {
            this.BuyAsync(currency, amount, null);
        }
        
        /// <remarks/>
        public void BuyAsync(Currencies currency, double amount, object userState) {
            if ((this.BuyOperationCompleted == null)) {
                this.BuyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBuyOperationCompleted);
            }
            this.InvokeAsync("Buy", new object[] {
                        currency,
                        amount}, this.BuyOperationCompleted, userState);
        }
        
        private void OnBuyOperationCompleted(object arg) {
            if ((this.BuyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BuyCompleted(this, new BuyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Fabrikam.com/Sell", RequestNamespace="http://Fabrikam.com", ResponseNamespace="http://Fabrikam.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public double Sell(Currencies currency, double amount) {
            object[] results = this.Invoke("Sell", new object[] {
                        currency,
                        amount});
            return ((double)(results[0]));
        }
        
        /// <remarks/>
        public void SellAsync(Currencies currency, double amount) {
            this.SellAsync(currency, amount, null);
        }
        
        /// <remarks/>
        public void SellAsync(Currencies currency, double amount, object userState) {
            if ((this.SellOperationCompleted == null)) {
                this.SellOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSellOperationCompleted);
            }
            this.InvokeAsync("Sell", new object[] {
                        currency,
                        amount}, this.SellOperationCompleted, userState);
        }
        
        private void OnSellOperationCompleted(object arg) {
            if ((this.SellCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SellCompleted(this, new SellCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.21006.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Fabrikam.com")]
    public enum Currencies {
        
        /// <remarks/>
        Dollar,
        
        /// <remarks/>
        Euro,
        
        /// <remarks/>
        Yen,
        
        /// <remarks/>
        Pound,
        
        /// <remarks/>
        Dinar,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.21006.1")]
    public delegate void BuyCompletedEventHandler(object sender, BuyCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.21006.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BuyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BuyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public double Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((double)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.21006.1")]
    public delegate void SellCompletedEventHandler(object sender, SellCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.21006.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SellCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SellCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public double Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((double)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591