//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketingOffice.UI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TicketingOffice.UI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string btn_Delete {
            get {
                return ResourceManager.GetString("btn_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find.
        /// </summary>
        public static string btn_Find {
            get {
                return ResourceManager.GetString("btn_Find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string btn_New {
            get {
                return ResourceManager.GetString("btn_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string btn_Save {
            get {
                return ResourceManager.GetString("btn_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete?.
        /// </summary>
        public static string ConfirmDeleteMessage {
            get {
                return ResourceManager.GetString("ConfirmDeleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string CustomerColumnHeader_Address {
            get {
                return ResourceManager.GetString("CustomerColumnHeader_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cell Number.
        /// </summary>
        public static string CustomerColumnHeader_Cell {
            get {
                return ResourceManager.GetString("CustomerColumnHeader_Cell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string CustomerColumnHeader_City {
            get {
                return ResourceManager.GetString("CustomerColumnHeader_City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string CustomerColumnHeader_Country {
            get {
                return ResourceManager.GetString("CustomerColumnHeader_Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birth Date.
        /// </summary>
        public static string CustomerColumnHeader_DOB {
            get {
                return ResourceManager.GetString("CustomerColumnHeader_DOB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string CustomerColumnHeader_Email {
            get {
                return ResourceManager.GetString("CustomerColumnHeader_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string CustomerColumnHeader_FirstName {
            get {
                return ResourceManager.GetString("CustomerColumnHeader_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string CustomerColumnHeader_LastName {
            get {
                return ResourceManager.GetString("CustomerColumnHeader_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        public static string CustomerColumnHeader_Phone {
            get {
                return ResourceManager.GetString("CustomerColumnHeader_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reduction Code.
        /// </summary>
        public static string CustomerColumnHeader_Reduction {
            get {
                return ResourceManager.GetString("CustomerColumnHeader_Reduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find by country.
        /// </summary>
        public static string InternalCRMWindow_FindCustomerLabel {
            get {
                return ResourceManager.GetString("InternalCRMWindow_FindCustomerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Customer details (Internal).
        /// </summary>
        public static string MainWindow_btnInternalCRM {
            get {
                return ResourceManager.GetString("MainWindow_btnInternalCRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Customer details (Private).
        /// </summary>
        public static string MainWindow_btnPrivateCRM {
            get {
                return ResourceManager.GetString("MainWindow_btnPrivateCRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get service notifications.
        /// </summary>
        public static string MainWindow_btnShowNotifications {
            get {
                return ResourceManager.GetString("MainWindow_btnShowNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order a ticket.
        /// </summary>
        public static string MainWindow_btnShowOrderTicket {
            get {
                return ResourceManager.GetString("MainWindow_btnShowOrderTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay for a ticket.
        /// </summary>
        public static string MainWindow_btnShowPayTicket {
            get {
                return ResourceManager.GetString("MainWindow_btnShowPayTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select an option.
        /// </summary>
        public static string MainWindow_SelectOptionLabel {
            get {
                return ResourceManager.GetString("MainWindow_SelectOptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        public static string MainWindow_txtPassword {
            get {
                return ResourceManager.GetString("MainWindow_txtPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name:.
        /// </summary>
        public static string MainWindow_txtUserName {
            get {
                return ResourceManager.GetString("MainWindow_txtUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase date:.
        /// </summary>
        public static string OrderItem_PurchaseDate {
            get {
                return ResourceManager.GetString("OrderItem_PurchaseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total price:.
        /// </summary>
        public static string OrderItem_TotalPrice {
            get {
                return ResourceManager.GetString("OrderItem_TotalPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get hall state (ASync client).
        /// </summary>
        public static string OrderTicketWindow_btnGelHallStateASyncClient {
            get {
                return ResourceManager.GetString("OrderTicketWindow_btnGelHallStateASyncClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get hall state (ASync server).
        /// </summary>
        public static string OrderTicketWindow_btnGelHallStateAsyncServer {
            get {
                return ResourceManager.GetString("OrderTicketWindow_btnGelHallStateAsyncServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get hall state.
        /// </summary>
        public static string OrderTicketWindow_btnGelHallStateSync {
            get {
                return ResourceManager.GetString("OrderTicketWindow_btnGelHallStateSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        public static string OrderTicketWindow_btnOrderTicket {
            get {
                return ResourceManager.GetString("OrderTicketWindow_btnOrderTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Ticketing Bridge.
        /// </summary>
        public static string OrderTicketWindow_chkUseTicketingBridge {
            get {
                return ResourceManager.GetString("OrderTicketWindow_chkUseTicketingBridge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the purchasing customer.
        /// </summary>
        public static string OrderTicketWindow_NoCustomerSelected {
            get {
                return ResourceManager.GetString("OrderTicketWindow_NoCustomerSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select your requested seats.
        /// </summary>
        public static string OrderTicketWindow_NoSeatSelected {
            get {
                return ResourceManager.GetString("OrderTicketWindow_NoSeatSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation completed successfully.
        /// </summary>
        public static string OrderTicketWindow_OperationCompleted {
            get {
                return ResourceManager.GetString("OrderTicketWindow_OperationCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the customer.
        /// </summary>
        public static string OrderTicketWindow_SelectCustomerLabel {
            get {
                return ResourceManager.GetString("OrderTicketWindow_SelectCustomerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected seats.
        /// </summary>
        public static string OrderTicketWindow_SelectedSeatsLabel {
            get {
                return ResourceManager.GetString("OrderTicketWindow_SelectedSeatsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the event.
        /// </summary>
        public static string OrderTicketWindow_SelectEventLabel {
            get {
                return ResourceManager.GetString("OrderTicketWindow_SelectEventLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the show.
        /// </summary>
        public static string OrderTicketWindow_SelectShowLabel {
            get {
                return ResourceManager.GetString("OrderTicketWindow_SelectShowLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card No.
        /// </summary>
        public static string PayTicketWindow_cmbCreditNumber {
            get {
                return ResourceManager.GetString("PayTicketWindow_cmbCreditNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type:.
        /// </summary>
        public static string PayTicketWindow_cmbPaymentType {
            get {
                return ResourceManager.GetString("PayTicketWindow_cmbPaymentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount must be floating number.
        /// </summary>
        public static string PayTicketWindow_NewPayment_NotDouble {
            get {
                return ResourceManager.GetString("PayTicketWindow_NewPayment_NotDouble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount must be positive.
        /// </summary>
        public static string PayTicketWindow_NewPayment_NotPositive {
            get {
                return ResourceManager.GetString("PayTicketWindow_NewPayment_NotPositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve payment.
        /// </summary>
        public static string PayTicketWindow_PaymentButton {
            get {
                return ResourceManager.GetString("PayTicketWindow_PaymentButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash.
        /// </summary>
        public static string PayTicketWindow_PaymentType_Cash {
            get {
                return ResourceManager.GetString("PayTicketWindow_PaymentType_Cash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cheque.
        /// </summary>
        public static string PayTicketWindow_PaymentType_Cheque {
            get {
                return ResourceManager.GetString("PayTicketWindow_PaymentType_Cheque", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Card.
        /// </summary>
        public static string PayTicketWindow_PaymentType_Credit {
            get {
                return ResourceManager.GetString("PayTicketWindow_PaymentType_Credit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voucher.
        /// </summary>
        public static string PayTicketWindow_PaymentType_Voucher {
            get {
                return ResourceManager.GetString("PayTicketWindow_PaymentType_Voucher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve refund.
        /// </summary>
        public static string PayTicketWindow_RefundButton {
            get {
                return ResourceManager.GetString("PayTicketWindow_RefundButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the customer.
        /// </summary>
        public static string PayTicketWindow_SelectCustomerLabel {
            get {
                return ResourceManager.GetString("PayTicketWindow_SelectCustomerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the order.
        /// </summary>
        public static string PayTicketWindow_SelectOrderLabel {
            get {
                return ResourceManager.GetString("PayTicketWindow_SelectOrderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a payment to refund, or enter a new payment.
        /// </summary>
        public static string PayTicketWindow_SelectPaymentLabel {
            get {
                return ResourceManager.GetString("PayTicketWindow_SelectPaymentLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount:.
        /// </summary>
        public static string PayTicketWindow_txtPaymentAmount {
            get {
                return ResourceManager.GetString("PayTicketWindow_txtPaymentAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A customer with the given Email and Cell number was not found.
        /// </summary>
        public static string PrivateCRMWindow_CustomerNotFound {
            get {
                return ResourceManager.GetString("PrivateCRMWindow_CustomerNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Listener.
        /// </summary>
        public static string ServiceNotificationWindow_btnListen {
            get {
                return ResourceManager.GetString("ServiceNotificationWindow_btnListen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register Duplex Service.
        /// </summary>
        public static string ServiceNotificationWindow_btnRegisterDuplex {
            get {
                return ResourceManager.GetString("ServiceNotificationWindow_btnRegisterDuplex", resourceCulture);
            }
        }
    }
}
