//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30128.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketingOffice.Common.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringsResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringsResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TicketingOffice.Common.Properties.StringsResource", typeof(StringsResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action failed. See inner exception..
        /// </summary>
        public static string ActionFailed {
            get {
                return ResourceManager.GetString("ActionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action not knows. Check the action header in the message and make sure in complies with the ticketing contract.
        /// </summary>
        public static string ActionNotKnown {
            get {
                return ResourceManager.GetString("ActionNotKnown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The amount paid is too large. .
        /// </summary>
        public static string AmountTooLarge {
            get {
                return ResourceManager.GetString("AmountTooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running {0} on thread {1}.
        /// </summary>
        public static string AsyncExecution {
            get {
                return ResourceManager.GetString("AsyncExecution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The header with the CallID was not found. Check the Http Bridge..
        /// </summary>
        public static string CallIDNotFound {
            get {
                return ResourceManager.GetString("CallIDNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating Service Hosts..
        /// </summary>
        public static string CreateHosts {
            get {
                return ResourceManager.GetString("CreateHosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Credit card was not approved for payment..
        /// </summary>
        public static string CreditCardNotApproved {
            get {
                return ResourceManager.GetString("CreditCardNotApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CustomerID Not Found..
        /// </summary>
        public static string CustomerIDNotFound {
            get {
                return ResourceManager.GetString("CustomerIDNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer {0} Not Found..
        /// </summary>
        public static string CustomerNotFound {
            get {
                return ResourceManager.GetString("CustomerNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not delete the {0} business entity. See inner exception. {1}.
        /// </summary>
        public static string DeleteError {
            get {
                return ResourceManager.GetString("DeleteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot delete theater. There are still reservations for it. Make sure all reservations are deleted..
        /// </summary>
        public static string DeleteTheaterFailed {
            get {
                return ResourceManager.GetString("DeleteTheaterFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The errorHandlerType specified in the ErrorBehaviorAttribute constructor must implement System.ServiceModel.Dispatcher.IErrorHandler.
        /// </summary>
        public static string ErrorHandlerMustImplementIErrorHandler {
            get {
                return ResourceManager.GetString("ErrorHandlerMustImplementIErrorHandler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The errorHandlerType specified in the ErrorBehaviorAttribute constructor must have a public empty constructor..
        /// </summary>
        public static string ErrorHandlerMustIncludeEmptyConstructor {
            get {
                return ResourceManager.GetString("ErrorHandlerMustIncludeEmptyConstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find the exact event. Please supply more info or che.
        /// </summary>
        public static string EventInfoNotFound {
            get {
                return ResourceManager.GetString("EventInfoNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event {0} NotFound.
        /// </summary>
        public static string EventNotFound {
            get {
                return ResourceManager.GetString("EventNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not contact client. See inner exception {0}.
        /// </summary>
        public static string FailedToContactClient {
            get {
                return ResourceManager.GetString("FailedToContactClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed To Contact Crm Service. Check configuration. Make sure the service is on..
        /// </summary>
        public static string FailedToContactCrm {
            get {
                return ResourceManager.GetString("FailedToContactCrm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed To Contact Currency Exchange Service. Check configuration. Make sure the service is on..
        /// </summary>
        public static string FailedToContactCurrencyExchange {
            get {
                return ResourceManager.GetString("FailedToContactCurrencyExchange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed To Contact HallState reservations Service. Check configuration. Make sure the service is on..
        /// </summary>
        public static string FailedToContactHallState {
            get {
                return ResourceManager.GetString("FailedToContactHallState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed To Contact Payment Service. Check configuration. Make sure the service is on..
        /// </summary>
        public static string FailedToContactPayment {
            get {
                return ResourceManager.GetString("FailedToContactPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed To Contact Price Rules Service. Check configuration. Make sure the service is on..
        /// </summary>
        public static string FailedToContactPriceRules {
            get {
                return ResourceManager.GetString("FailedToContactPriceRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed To Contact Pricing Service. Check configuration. Make sure the service is on..
        /// </summary>
        public static string FailedToContactPricing {
            get {
                return ResourceManager.GetString("FailedToContactPricing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed To Contact Shows Service. Check configuration. Make sure the service is on..
        /// </summary>
        public static string FailedToContactShows {
            get {
                return ResourceManager.GetString("FailedToContactShows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed To Contact Ticketing Service. Check configuration. Make sure the service is on..
        /// </summary>
        public static string FailedToContactTicketing {
            get {
                return ResourceManager.GetString("FailedToContactTicketing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed To Contact Ticketing bridge Service. Check configuration. Make sure the service is on..
        /// </summary>
        public static string FailedToContactTicketingBridge {
            get {
                return ResourceManager.GetString("FailedToContactTicketingBridge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Hall {0} was not found..
        /// </summary>
        public static string HallNotFound {
            get {
                return ResourceManager.GetString("HallNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host {0} Closed..
        /// </summary>
        public static string HostClosed {
            get {
                return ResourceManager.GetString("HostClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host {0} Created..
        /// </summary>
        public static string HostCreated {
            get {
                return ResourceManager.GetString("HostCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host {0} creation failed. Exception: {1}.
        /// </summary>
        public static string HostCreationFailed {
            get {
                return ResourceManager.GetString("HostCreationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host Halted {0}.
        /// </summary>
        public static string HostFalted {
            get {
                return ResourceManager.GetString("HostFalted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host {0} Started..
        /// </summary>
        public static string HostStarted {
            get {
                return ResourceManager.GetString("HostStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting the host {0} failed. Exception: {1} .
        /// </summary>
        public static string HostStartFailed {
            get {
                return ResourceManager.GetString("HostStartFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not insert the {0} business entity. See inner exception. {1}.
        /// </summary>
        public static string InsertError {
            get {
                return ResourceManager.GetString("InsertError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Customer..
        /// </summary>
        public static string InvalidCustomer {
            get {
                return ResourceManager.GetString("InvalidCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid or closed Event. Check if the event is open..
        /// </summary>
        public static string InvalidOrClosedEvent {
            get {
                return ResourceManager.GetString("InvalidOrClosedEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Pricing Rule. Check the reduction and dates. .
        /// </summary>
        public static string InvalidPricingRule {
            get {
                return ResourceManager.GetString("InvalidPricingRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Seat or Row number..
        /// </summary>
        public static string InvalidSeatOrRow {
            get {
                return ResourceManager.GetString("InvalidSeatOrRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid seats string. There is an odd number of elements. .
        /// </summary>
        public static string InvalidSeatsString {
            get {
                return ResourceManager.GetString("InvalidSeatsString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TheaterID cannot be negative or zero..
        /// </summary>
        public static string InvalidTheaterID {
            get {
                return ResourceManager.GetString("InvalidTheaterID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listening at: {0}..
        /// </summary>
        public static string ListentingAt {
            get {
                return ResourceManager.GetString("ListentingAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The method {0} was called by {1}.
        /// </summary>
        public static string MethodCalledBy {
            get {
                return ResourceManager.GetString("MethodCalledBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More Than One Customer was found.
        /// </summary>
        public static string MoreThanOneCustomerWasFound {
            get {
                return ResourceManager.GetString("MoreThanOneCustomerWasFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSMQ queue creation failed check the queue path and permissions.
        /// </summary>
        public static string MSMQCreationFailed {
            get {
                return ResourceManager.GetString("MSMQCreationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order must have seats..
        /// </summary>
        public static string NoSeatsInOrder {
            get {
                return ResourceManager.GetString("NoSeatsInOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer is null.
        /// </summary>
        public static string NullCustomer {
            get {
                return ResourceManager.GetString("NullCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event cannot be null..
        /// </summary>
        public static string NullEvent {
            get {
                return ResourceManager.GetString("NullEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order is null.
        /// </summary>
        public static string NullOrder {
            get {
                return ResourceManager.GetString("NullOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show cannot be null..
        /// </summary>
        public static string NullShow {
            get {
                return ResourceManager.GetString("NullShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order already approved cannot preform payment.
        /// </summary>
        public static string OrderAlreadyApproved {
            get {
                return ResourceManager.GetString("OrderAlreadyApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order {0} Not Found.
        /// </summary>
        public static string OrderNotFound {
            get {
                return ResourceManager.GetString("OrderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not execute payment. Invalid User Details.
        /// </summary>
        public static string PaymentFailedInvalidUserDetails {
            get {
                return ResourceManager.GetString("PaymentFailedInvalidUserDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not execute payment. Order not found..
        /// </summary>
        public static string PaymentFailedOrderNotFound {
            get {
                return ResourceManager.GetString("PaymentFailedOrderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price Calculation failed. Look at the inner exception..
        /// </summary>
        public static string PricingFailed {
            get {
                return ResourceManager.GetString("PricingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pricing rule was not found. Check the config file..
        /// </summary>
        public static string PricingRuleNotFound {
            get {
                return ResourceManager.GetString("PricingRuleNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot refund a negative amount.
        /// </summary>
        public static string RefundFailedNegativeAmount {
            get {
                return ResourceManager.GetString("RefundFailedNegativeAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not execute refund. Order not found..
        /// </summary>
        public static string RefundFailedOrderNotFound {
            get {
                return ResourceManager.GetString("RefundFailedOrderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not execute refund. Payment not found..
        /// </summary>
        public static string RefundFailedPaymentNotFound {
            get {
                return ResourceManager.GetString("RefundFailedPaymentNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not reserve seat. The event does not exist. Check the eventID ..
        /// </summary>
        public static string ReservationFailedEventDoesNotExist {
            get {
                return ResourceManager.GetString("ReservationFailedEventDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservation Failed. The hall / theater was not found..
        /// </summary>
        public static string ReservationFailedTheaterNotFound {
            get {
                return ResourceManager.GetString("ReservationFailedTheaterNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservation {0} NotFound..
        /// </summary>
        public static string ReservationNotFound {
            get {
                return ResourceManager.GetString("ReservationNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not retrieve the {0} business entity. See inner exception. {1}.
        /// </summary>
        public static string RetrieveError {
            get {
                return ResourceManager.GetString("RetrieveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservation Failed. The seat is already taken..
        /// </summary>
        public static string SeatAlreadyTaken {
            get {
                return ResourceManager.GetString("SeatAlreadyTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in parsing seat numbers..
        /// </summary>
        public static string SeatParsingError {
            get {
                return ResourceManager.GetString("SeatParsingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No services where found in the configuration file..
        /// </summary>
        public static string SevicesToHostNotFound {
            get {
                return ResourceManager.GetString("SevicesToHostNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show must have a name..
        /// </summary>
        public static string ShowMustHaveAName {
            get {
                return ResourceManager.GetString("ShowMustHaveAName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show {0} Not Found..
        /// </summary>
        public static string ShowNotFound {
            get {
                return ResourceManager.GetString("ShowNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting Sevices Hosts..
        /// </summary>
        public static string StatrtHosts {
            get {
                return ResourceManager.GetString("StatrtHosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopping Service Hosts..
        /// </summary>
        public static string StoppingHosts {
            get {
                return ResourceManager.GetString("StoppingHosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticketing failed see inner exception..
        /// </summary>
        public static string TicketingFailed {
            get {
                return ResourceManager.GetString("TicketingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not authorized to perform this operation..
        /// </summary>
        public static string UnAuthorizedOperation {
            get {
                return ResourceManager.GetString("UnAuthorizedOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not update the {0} business entity. See inner exception. {1}.
        /// </summary>
        public static string UpdateError {
            get {
                return ResourceManager.GetString("UpdateError", resourceCulture);
            }
        }
    }
}
