//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace TicketingOffice.PricingRules.DataAccess
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class TicketingOfficePricingEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new TicketingOfficePricingEntities object using the connection string found in the 'TicketingOfficePricingEntities' section of the application configuration file.
        /// </summary>
        public TicketingOfficePricingEntities() : base("name=TicketingOfficePricingEntities", "TicketingOfficePricingEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new TicketingOfficePricingEntities object.
        /// </summary>
        public TicketingOfficePricingEntities(string connectionString) : base(connectionString, "TicketingOfficePricingEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new TicketingOfficePricingEntities object.
        /// </summary>
        public TicketingOfficePricingEntities(EntityConnection connection) : base(connection, "TicketingOfficePricingEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<PricingRule> PricingRules
        {
            get
            {
                if ((_PricingRules == null))
                {
                    _PricingRules = base.CreateObjectSet<PricingRule>("PricingRules");
                }
                return _PricingRules;
            }
        }
        private ObjectSet<PricingRule> _PricingRules;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the PricingRules EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPricingRules(PricingRule pricingRule)
        {
            base.AddObject("PricingRules", pricingRule);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TicketingOfficeModel", Name="PricingRule")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class PricingRule : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new PricingRule object.
        /// </summary>
        /// <param name="ruleID">Initial value of the RuleID property.</param>
        /// <param name="policyName">Initial value of the PolicyName property.</param>
        /// <param name="reduction">Initial value of the Reduction property.</param>
        public static PricingRule CreatePricingRule(global::System.Int32 ruleID, global::System.String policyName, global::System.Byte reduction)
        {
            PricingRule pricingRule = new PricingRule();
            pricingRule.RuleID = ruleID;
            pricingRule.PolicyName = policyName;
            pricingRule.Reduction = reduction;
            return pricingRule;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 RuleID
        {
            get
            {
                return _RuleID;
            }
            set
            {
                if (_RuleID != value)
                {
                    OnRuleIDChanging(value);
                    ReportPropertyChanging("RuleID");
                    _RuleID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("RuleID");
                    OnRuleIDChanged();
                }
            }
        }
        private global::System.Int32 _RuleID;
        partial void OnRuleIDChanging(global::System.Int32 value);
        partial void OnRuleIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String PolicyName
        {
            get
            {
                return _PolicyName;
            }
            set
            {
                OnPolicyNameChanging(value);
                ReportPropertyChanging("PolicyName");
                _PolicyName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("PolicyName");
                OnPolicyNameChanged();
            }
        }
        private global::System.String _PolicyName;
        partial void OnPolicyNameChanging(global::System.String value);
        partial void OnPolicyNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ReductionCode
        {
            get
            {
                return _ReductionCode;
            }
            set
            {
                OnReductionCodeChanging(value);
                ReportPropertyChanging("ReductionCode");
                _ReductionCode = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ReductionCode");
                OnReductionCodeChanged();
            }
        }
        private Nullable<global::System.Int32> _ReductionCode;
        partial void OnReductionCodeChanging(Nullable<global::System.Int32> value);
        partial void OnReductionCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte Reduction
        {
            get
            {
                return _Reduction;
            }
            set
            {
                OnReductionChanging(value);
                ReportPropertyChanging("Reduction");
                _Reduction = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Reduction");
                OnReductionChanged();
            }
        }
        private global::System.Byte _Reduction;
        partial void OnReductionChanging(global::System.Byte value);
        partial void OnReductionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> FromDate
        {
            get
            {
                return _FromDate;
            }
            set
            {
                OnFromDateChanging(value);
                ReportPropertyChanging("FromDate");
                _FromDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FromDate");
                OnFromDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _FromDate;
        partial void OnFromDateChanging(Nullable<global::System.DateTime> value);
        partial void OnFromDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> ToDate
        {
            get
            {
                return _ToDate;
            }
            set
            {
                OnToDateChanging(value);
                ReportPropertyChanging("ToDate");
                _ToDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ToDate");
                OnToDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _ToDate;
        partial void OnToDateChanging(Nullable<global::System.DateTime> value);
        partial void OnToDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> MinNumOfOrders
        {
            get
            {
                return _MinNumOfOrders;
            }
            set
            {
                OnMinNumOfOrdersChanging(value);
                ReportPropertyChanging("MinNumOfOrders");
                _MinNumOfOrders = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MinNumOfOrders");
                OnMinNumOfOrdersChanged();
            }
        }
        private Nullable<global::System.Int32> _MinNumOfOrders;
        partial void OnMinNumOfOrdersChanging(Nullable<global::System.Int32> value);
        partial void OnMinNumOfOrdersChanged();

        #endregion
    
    }

    #endregion
    
}
